global.Registry = (function Registry() {
  const wines = [
    "violetcoloured:red_grape_juice",
    "violetcoloured:white_grape_juice",
    "violetcoloured:apple_juice",
    "vinery:apple_cider",
    "vinery:apple_wine",
    "vinery:mellohi_wine",
    "vinery:glowing_wine",
    "vinery:solaris_wine",
    "vinery:noir_wine",
    "vinery:red_wine",
    "vinery:strad_wine",
    "vinery:cherry_wine",
    "vinery:cristel_wine",
    "vinery:creepers_crush",
    "vinery:kelp_cider",
    "vinery:lilitu_wine",
    "vinery:jo_special_mixture",
    "vinery:eiswein",
    "vinery:aegis_wine",
    "vinery:bolvar_wine",
    "vinery:chorus_wine",
    "vinery:villagers_fright",
    "vinery:clark_wine",
    "vinery:magnetic_wine",
    "vinery:stal_wine",
    "vinery:chenet_wine",
    "vinery:bottle_mojang_noir",
    "vinery:jellie_wine",
  ];

  const fermentedDrinks = [
    "brewinandchewin:beer",
    "brewinandchewin:vodka",
    "brewinandchewin:mead",
    "brewinandchewin:rice_wine",
    "brewinandchewin:egg_grog",
    "brewinandchewin:strongroot_ale",
    "brewinandchewin:saccharine_rum",
    "brewinandchewin:pale_jane",
    "brewinandchewin:salty_folly",
    "brewinandchewin:steel_toe_stout",
    "brewinandchewin:glittering_grenadine",
    "brewinandchewin:bloody_mary",
    "brewinandchewin:red_rum",
    "brewinandchewin:withering_dross",
    "brewinandchewin:dread_nog",
  ];

  const potionEffects = [
    "minecraft:fire_resistance",
    "minecraft:infested",
    "minecraft:invisibility",
    "minecraft:jump_boost",
    "minecraft:night_vision",
    "minecraft:oozing",
    "minecraft:poison",
    "minecraft:regeneration",
    "minecraft:resistance",
    "minecraft:slow_falling",
    "minecraft:slowness",
    "minecraft:speed",
    "minecraft:strength",
    "minecraft:water_breathing",
    "minecraft:weakness",
    "minecraft:weaving",
    "minecraft:wind_charged",
  ];

  const otherEffects = [
    "minecraft:absorption",
    "minecraft:bad_omen",
    "minecraft:blindness",
    "minecraft:conduit_power",
    "minecraft:darkness",
    "minecraft:dolphins_grace",
    "minecraft:glowing",
    "minecraft:haste",
    "minecraft:hero_of_the_village",
    "minecraft:hunger",
    "minecraft:levitation",
    "minecraft:mining_fatigue",
    "minecraft:nausea",
    "minecraft:raid_omen",
    "minecraft:trial_omen",
    "minecraft:wither",
  ];

  return {
    wines: wines,
    fermentedDrinks: fermentedDrinks,
    potionEffects: potionEffects,
    otherEffects: otherEffects,
  };
})();
